---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: '/Users/smukundhan/Documents/vagrant_centOS/centOS/cookbooks/test-apache1/roles'
  environments_path: '/Users/smukundhan/Documents/vagrant_centOS/centOS/cookbooks/test-apache1/environments'
  nodes_path: '/Users/smukundhan/Documents/vagrant_centOS/centOS/cookbooks/test-apache1/nodes'
  client_rb:
    environment: edge_dev

platforms:
  - name: centos-6.4
    driver:
      customize:
        memory: 1024

suites:
  - name: default
    run_list:
      - recipe[test-apache1::default]
    attributes:
  - name: pdevedgws300.ie.intu.net
    run_list:
      - recipe[test-apache1::default]
    attributes:
  - name: pdevedgas300.ie.intu.net
    run_list:
      - recipe[test-apache1::default]
